@baseUrl = http://localhost:3333
@token = {{signin.response.body.accessToken}}

###

# @name signin
POST {{baseUrl}}/sign-in
Content-Type: application/json
Accept: application/json

{
    "email": "rafael@teste.com",
    "password": "123456"
}

###

# @name create-user
POST {{baseUrl}}/users
Content-Type: application/json
Accept: application/json

{
    "name": "Teste",
    "email": "tatiane@teste.com",

    "role": "admin"
}


###

# @name me
GET {{baseUrl}}/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
###

# @name update-user
PUT {{baseUrl}}/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "Rafael Tiburcio",
    "email": "rafael@teste.com",
    "password": "123456",
    "role": "admin"
}
